name: Publish Elasticsearch container image

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: elasticsearch
  ES_VER: 7.10.2

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image And Push
        uses: docker/build-push-action@v2
        with:
          context: ./elasticsearch
          file: ./elasticsearch/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: ES_VER=${{ env.ES_VER }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:v${{ env.ES_VER }}, ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest